services:
  db:
    image: postgres
    container_name: ${DB_NAME}-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev}
      POSTGRES_DB: ${DB_NAME:-app}
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/${DB_NAME}:/var/lib/postgresql/data
#   pgadmin:
#     image: dpage/pgadmin4

#     container_name: ${DB_NAME}-pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db

# volumes:
#   postgres_data:
